services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbixpass
      - POSTGRES_DB=zabbix
    volumes:
      - ./zabbix-postgres:/var/lib/postgresql/data
    restart: unless-stopped

  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbixpass
    depends_on:
      - postgres
    ports:
      - '10051:10051'
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbixpass
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Asia/Jakarta
    ports:
      - '8080:8080'
    depends_on:
      - zabbix-server
    restart: unless-stopped

  zabbix-agent:
    image: zabbix/zabbix-agent
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_HOSTNAME=zabbix-agent-1
    restart: unless-stopped
